### ISSUE TITLE
Add multiple element in same page

### ISSUE THREAD

**Issue by Paul75** [klinker24/Android-FloatingTutorialActivity#2]
Hello,

It is possible to have in one page and send to activity two elements ?

Exemple : 
- stars
- EditText

When can I do this ?

thanks

**Comment by klinker24** [comment]
Sorry I don't understand what you mean by that. The pages are just defined by XML attributes, all it really is, is a Fragment. So yes, you can put whatever UI elements you want, into it.

**Comment by klinker24** [comment]
Yes, it is just a normal intent that you are returning to the calling activity. It works the same way as any other activity that provides a result.

https://github.com/klinker24/Android-FloatingTutorialActivity/blob/a04a2ea82815a3da0dfb48162d2efc2eb219cdb3/sample-kotlin/src/main/java/xyz/klinker/floating_tutorial/examples/SelectionDialogExample.kt#L64

**Comment by Paul75** [comment]
yes but means I must do in onclicklistener on my ratingBar ? and on addTextChangedListener for the EditText ?
like : 

```
findViewById<BaseRatingBar>(R.id.rating).setOnRatingChangeListener { baseRatingBar: BaseRatingBar, fl: Float ->
                    val resultData = Intent()
                    resultData.putExtra(RESULT_DATA_STARS, fl)
                    setResult(Activity.RESULT_OK, resultData)
                }

                findViewById<AppCompatEditText>(R.id.editComment).addTextChangedListener(object : TextWatcher {
                    override fun afterTextChanged(p0: Editable?) {
                        val resultData = Intent()
                        resultData.putExtra(RESULT_DATA_COMMENT, p0.toString())
                        setResult(Activity.RESULT_OK, resultData)
                    }

                    override fun beforeTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
                    }

                    override fun onTextChanged(p0: CharSequence?, p1: Int, p2: Int, p3: Int) {
                    }
                })
```

Thanks

**Comment by klinker24** [comment]
You can only set the result once, and you need to include both pieces of data in the intent. I think that you should look up some information on getting the result from the activity. My library does not do it any differently than Android does.

https://developer.android.com/training/basics/intents/result

```kotlin
val resultData = Intent()
resultData.putExtra(RESULT_DATA_STARS, stars)
resultData.putExtra(RESULT_DATA_COMMENT, editComment.text.toString())
setResult(Activity.RESULT_OK, resultData)
```

**Comment by Paul75** [comment]
strenge that when I do in the my post works I retreive all the two element ...
